config/routes.rb
Rails.application.routes.draw do
  devise_for :system_users, path: 'auth'
  root 'products#index'
  resources :system_users
  resources :products

  resources :base_classifieds

  resources :base_periods

  resources :base_series

  resources :base_sizes

  resources :base_colors

  resources :base_categories

  resources :base_customers

end

app/models/base_category.rb
class BaseCategory < ActiveRecord::Base
end

app/models/base_classified.rb
class BaseClassified < ActiveRecord::Base
end

app/models/base_color.rb
class BaseColor < ActiveRecord::Base
end

app/models/base_customer.rb
class BaseCustomer < ActiveRecord::Base
end

app/models/base_period.rb
class BasePeriod < ActiveRecord::Base
end

app/models/base_series.rb
class BaseSeries < ActiveRecord::Base
end

app/models/base_size.rb
class BaseSize < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/product_color.rb
class ProductColor < ActiveRecord::Base
  belongs_to :product
  belongs_to :base_color
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
end

app/models/product_size.rb
class ProductSize < ActiveRecord::Base
  belongs_to :product
  belongs_to :base_size
end

app/models/product_star.rb
class ProductStar < ActiveRecord::Base
  belongs_to :product
  belongs_to :product_color
  belongs_to :base_customer
end

app/models/system_user.rb
class SystemUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/base_classifieds_controller.rb
class BaseClassifiedsController < ApplicationController
  before_action :set_base_classified, only: [:show, :edit, :update, :destroy]

  # GET /base_classifieds
  # GET /base_classifieds.json
  def index
    @base_classifieds = BaseClassified.all
  end

  # GET /base_classifieds/1
  # GET /base_classifieds/1.json
  def show
  end

  # GET /base_classifieds/new
  def new
    @base_classified = BaseClassified.new
  end

  # GET /base_classifieds/1/edit
  def edit
  end

  # POST /base_classifieds
  # POST /base_classifieds.json
  def create
    @base_classified = BaseClassified.new(base_classified_params)

    respond_to do |format|
      if @base_classified.save
        format.html { redirect_to @base_classified, notice: 'Base classified was successfully created.' }
        format.json { render :show, status: :created, location: @base_classified }
      else
        format.html { render :new }
        format.json { render json: @base_classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /base_classifieds/1
  # PATCH/PUT /base_classifieds/1.json
  def update
    respond_to do |format|
      if @base_classified.update(base_classified_params)
        format.html { redirect_to @base_classified, notice: 'Base classified was successfully updated.' }
        format.json { render :show, status: :ok, location: @base_classified }
      else
        format.html { render :edit }
        format.json { render json: @base_classified.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /base_classifieds/1
  # DELETE /base_classifieds/1.json
  def destroy
    @base_classified.destroy
    respond_to do |format|
      format.html { redirect_to base_classifieds_url, notice: 'Base classified was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_classified
      @base_classified = BaseClassified.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def base_classified_params
      params.require(:base_classified).permit(:code, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_categories_helper.rb
module BaseCategoriesHelper
end

app/helpers/base_classifieds_helper.rb
module BaseClassifiedsHelper
end

app/helpers/base_colors_helper.rb
module BaseColorsHelper
end

app/helpers/base_customers_helper.rb
module BaseCustomersHelper
end

app/helpers/base_periods_helper.rb
module BasePeriodsHelper
end

app/helpers/base_series_helper.rb
module BaseSeriesHelper
end

app/helpers/base_sizes_helper.rb
module BaseSizesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/base_classifieds/_form.html.erb
<%= form_for(@base_classified) do |f| %>
  <% if @base_classified.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@base_classified.errors.count, "error") %> prohibited this base_classified from being saved:</h2>

      <ul>
      <% @base_classified.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/base_classifieds/edit.html.erb
<h1>Editing base_classified</h1>

<%= render 'form' %>

<%= link_to 'Show', @base_classified %> |
<%= link_to 'Back', base_classifieds_path %>

app/views/base_classifieds/index.html.erb
<h1>Listing base_classifieds</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @base_classifieds.each do |base_classified| %>
      <tr>
        <td><%= base_classified.code %></td>
        <td><%= base_classified.name %></td>
        <td><%= link_to 'Show', base_classified %></td>
        <td><%= link_to 'Edit', edit_base_classified_path(base_classified) %></td>
        <td><%= link_to 'Destroy', base_classified, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Base classified', new_base_classified_path %>

app/views/base_classifieds/new.html.erb
<h1>New base_classified</h1>

<%= render 'form' %>

<%= link_to 'Back', base_classifieds_path %>

app/views/base_classifieds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @base_classified.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @base_classified.name %>
</p>

<%= link_to 'Edit', edit_base_classified_path(@base_classified) %> |
<%= link_to 'Back', base_classifieds_path %>