config/routes.rb
Rails.application.routes.draw do
  devise_for :system_users, path: 'auth'
  root 'products#index'
  resources :system_users
  resources :products

  resources :base_classifieds

  resources :base_periods

  resources :base_series

  resources :base_sizes

  resources :base_colors

  resources :base_categories

  resources :base_customers

end

app/models/base_category.rb
class BaseCategory < ActiveRecord::Base
end

app/models/base_classified.rb
class BaseClassified < ActiveRecord::Base
end

app/models/base_color.rb
class BaseColor < ActiveRecord::Base
end

app/models/base_customer.rb
class BaseCustomer < ActiveRecord::Base
end

app/models/base_period.rb
class BasePeriod < ActiveRecord::Base
end

app/models/base_series.rb
class BaseSeries < ActiveRecord::Base
end

app/models/base_size.rb
class BaseSize < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/product_color.rb
class ProductColor < ActiveRecord::Base
  belongs_to :product
  belongs_to :base_color
end

app/models/product_image.rb
class ProductImage < ActiveRecord::Base
  belongs_to :product
end

app/models/product_size.rb
class ProductSize < ActiveRecord::Base
  belongs_to :product
  belongs_to :base_size
end

app/models/product_star.rb
class ProductStar < ActiveRecord::Base
  belongs_to :product
  belongs_to :product_color
  belongs_to :base_customer
end

app/models/system_user.rb
class SystemUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/base_categories_controller.rb
class BaseCategoriesController < ApplicationController
  before_action :set_base_category, only: [:show, :edit, :update, :destroy]

  # GET /base_categories
  # GET /base_categories.json
  def index
    @base_categories = BaseCategory.all
  end

  # GET /base_categories/1
  # GET /base_categories/1.json
  def show
  end

  # GET /base_categories/new
  def new
    @base_category = BaseCategory.new
  end

  # GET /base_categories/1/edit
  def edit
  end

  # POST /base_categories
  # POST /base_categories.json
  def create
    @base_category = BaseCategory.new(base_category_params)

    respond_to do |format|
      if @base_category.save
        format.html { redirect_to @base_category, notice: 'Base category was successfully created.' }
        format.json { render :show, status: :created, location: @base_category }
      else
        format.html { render :new }
        format.json { render json: @base_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /base_categories/1
  # PATCH/PUT /base_categories/1.json
  def update
    respond_to do |format|
      if @base_category.update(base_category_params)
        format.html { redirect_to @base_category, notice: 'Base category was successfully updated.' }
        format.json { render :show, status: :ok, location: @base_category }
      else
        format.html { render :edit }
        format.json { render json: @base_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /base_categories/1
  # DELETE /base_categories/1.json
  def destroy
    @base_category.destroy
    respond_to do |format|
      format.html { redirect_to base_categories_url, notice: 'Base category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_base_category
      @base_category = BaseCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def base_category_params
      params.require(:base_category).permit(:parent_id, :code, :name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_system_user!

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:number, :name, :size_class, :price, :series_id, :period_id, :classified_id, :category_id, :sub_category_id, :recommended_level, :description_fabric, :description_style, :if_ordering, :if_replenishing, :if_onsale, :if_preselection, :sex, :catena, :topdate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_categories_helper.rb
module BaseCategoriesHelper
end

app/helpers/base_colors_helper.rb
module BaseColorsHelper
end

app/helpers/base_customers_helper.rb
module BaseCustomersHelper
end

app/helpers/base_periods_helper.rb
module BasePeriodsHelper
end

app/helpers/base_series_helper.rb
module BaseSeriesHelper
end

app/helpers/base_sizes_helper.rb
module BaseSizesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/base_categories/_form.html.erb
<%= form_for(@base_category) do |f| %>
  <% if @base_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@base_category.errors.count, "error") %> prohibited this base_category from being saved:</h2>

      <ul>
      <% @base_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/base_categories/edit.html.erb
<h1>Editing base_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @base_category %> |
<%= link_to 'Back', base_categories_path %>

app/views/base_categories/index.html.erb
<h1>Listing base_categories</h1>

<table>
  <thead>
    <tr>
      <th>Parent</th>
      <th>Code</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @base_categories.each do |base_category| %>
      <tr>
        <td><%= base_category.parent_id %></td>
        <td><%= base_category.code %></td>
        <td><%= base_category.name %></td>
        <td><%= link_to 'Show', base_category %></td>
        <td><%= link_to 'Edit', edit_base_category_path(base_category) %></td>
        <td><%= link_to 'Destroy', base_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Base category', new_base_category_path %>

app/views/base_categories/new.html.erb
<h1>New base_category</h1>

<%= render 'form' %>

<%= link_to 'Back', base_categories_path %>

app/views/base_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parent:</strong>
  <%= @base_category.parent_id %>
</p>

<p>
  <strong>Code:</strong>
  <%= @base_category.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @base_category.name %>
</p>

<%= link_to 'Edit', edit_base_category_path(@base_category) %> |
<%= link_to 'Back', base_categories_path %>